In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from hottbox.core import Tensor, TensorCPD, TensorTKD

[Return to Table of Contents](./0_Table_of_contents.ipynb)

# Efficient representation of multidimensional arrays

A tensor of order $N$ is said to be of **rank-1** if it can be represented as an outer product of $N$ vectors. 

The figure below illustrates an example of a rank-1 tensor $\mathbf{\underline{X}}$ and provides intuition on how to compute the operation of outer product:

<img src="./imgs/outerproduct.png" alt="Drawing" style="width: 500px;"/>


# Kruskal representation

For a third order tensor or rank $R$ the Kruskal representation can be expressed as follows:

$$
\mathbf{\underline{X}} = \sum_{r=1}^R \mathbf{\underline{X}}_r = \sum_{r=1}^R \lambda_{r} \cdot \mathbf{a}_r \circ \mathbf{b}_r \circ \mathbf{c}_r
$$

The vectors $\mathbf{a}_r, \mathbf{b}_r$ and $\mathbf{c}_r$ are oftentime combined into the corresponding **factor matrices**:

$$
\mathbf{A} = \Big[ \mathbf{a}_1 \cdots \mathbf{a}_R \Big] \quad
\mathbf{B} = \Big[ \mathbf{b}_1 \cdots \mathbf{b}_R \Big] \quad
\mathbf{C} = \Big[ \mathbf{c}_1 \cdots \mathbf{c}_R \Big] \quad
$$

Thus, if we employ the mode-$n$ product, the **Kruskal representation** takes the form:

$$
\mathbf{\underline{X}} = \mathbf{\underline{\Lambda}} \times_1 \mathbf{A} \times_2 \mathbf{B} \times_3 \mathbf{C} = \Big[\mathbf{\underline{\Lambda}}; \mathbf{A}, \mathbf{B}, \mathbf{C} \Big]
$$

where the elements on the super-diagonal of the core tensor $\mathbf{\underline{\Lambda}}$ are occupied by the values $\lambda_r$ and all other entries are equal to zero. This can be visualised as shown on figure below:

<img src="./imgs/TensorCPD.png" alt="Drawing" style="width: 500px;"/>


In [3]:
# Create factor matrices
I, J, K = 3, 4, 5
R = 2

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

Kruskal representation of a tensor with rank=(2,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (3, 4, 5) features respectively.


## **Assigment 1**

1. What is the order of a tensor if its Kruskal representation consists of 5 factor matrices.

2. What is the order of a tensor if its Kruskal representation consists of core tensor which has only 5 elements on the super-diagonal.

3. For a 3-rd order tensor that consists of 500 elements, provide three different Kruskal representations.

4. For a tensor that consits of 1000 elements, provide three Kruskal representations, each of which should have different number of factor matrices.

5. For a 4-th order tensor that consists of 2401 elements, provide Kruskal representation if its core tensor consisting of 81 elements.


### Solution: Part 1

In [4]:
answer_1_1 = "The tensor is of order 5 if its Kruskal representation consists of 5 factor matrices"  # use this variable for your answer

print(answer_1_1)

ANSWER GOES HERE


### Solution: Part 2

In [5]:
answer_1_2 = "The order of a tensor is not related to the rank determined by the elements on the super diagonal. Therefore it is not possible to infer on the order of the tensor"  # use this variable for your answer

print(answer_1_2)

ANSWER GOES HERE


### Solution: Part 3

In [8]:
# First representation
I, J, K = 5, 10, 10  # define shape of the tensor in full form
R = 4              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 10, 10) features respectively.
This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (5, 10, 10) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [9]:
# Second representation
I, J, K = 5, 10, 10  # define shape of the tensor in full form
R = 3              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (2, 5, 50) features respectively.
This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (2, 5, 50) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [10]:
# Third representation
I, J, K = 5, 10, 10  # define shape of the tensor in full form
R = 6              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (25, 5, 4) features respectively.
This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (25, 5, 4) and ['mode-0', 'mode-1', 'mode-2'] respectively.


### Solution: Part 4

In [11]:
# First representation
I, J, K = 10, 10, 10  # define shape of the tensor in full form
R = 4              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (10, 10, 10) features respectively.
This tensor is of order 3 and consists of 1000 elements.
Sizes and names of its modes are (10, 10, 10) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [12]:
# Second representation
I, J, K, T = 10, 10, 5, 2  # define shape of the tensor in full form
R = 4              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
D = np.arange(T * R).reshape(T, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C, D], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (10, 10, 5, 2) features respectively.
This tensor is of order 4 and consists of 1000 elements.
Sizes and names of its modes are (10, 10, 5, 2) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


In [13]:
# Third representation
I, J, K, T, H = 10, 5, 5, 2, 2  # define shape of the tensor in full form
R = 4              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
D = np.arange(T * R).reshape(T, R)
E = np.arange(H * R).reshape(H, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C, D, E], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3', 'mode-4']
With corresponding latent components described by (10, 5, 5, 2, 2) features respectively.
This tensor is of order 5 and consists of 1000 elements.
Sizes and names of its modes are (10, 5, 5, 2, 2) and ['mode-0', 'mode-1', 'mode-2', 'mode-3', 'mode-4'] respectively.


### Solution: Part 5

In [15]:
# Provide Kruskal representation here
I, J, K, T = 7, 7, 7, 7  # define shape of the tensor in full form
R = 3              # define Kryskal rank of a tensor in CP form 

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
D = np.arange(T * R).reshape(T, R)
values = np.arange(R)

tensor_cpd = TensorCPD(fmat=[A, B, C, D], core_values=values)
print(tensor_cpd)

tensor_full = tensor_cpd.reconstruct()
print(tensor_full)

print('\n\tCore tensor')
print(tensor_cpd.core)
tensor_cpd.core.data

Kruskal representation of a tensor with rank=(3,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (7, 7, 7, 7) features respectively.
This tensor is of order 4 and consists of 2401 elements.
Sizes and names of its modes are (7, 7, 7, 7) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.

	Core tensor
This tensor is of order 4 and consists of 81 elements.
Sizes and names of its modes are (3, 3, 3, 3) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 1., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 2.]]]])

# Tucker representation



<img src="./imgs/TensorTKD.png" alt="Drawing" style="width: 600px;"/>

For a tensor $\mathbf{\underline{X}} \in \mathbb{R}^{I \times J \times K}$ illustrated above, the **Tucker form** represents the tensor in hand through a dense core tensor $\mathbf{\underline{G}}$ with multi-linear rank ($Q, R, P$) and a set of accompanying factor matrices $\mathbf{A} \in \mathbb{R}^{I \times Q}, \mathbf{B} \in \mathbb{R}^{J \times R}$ and $\mathbf{C} \in \mathbb{R}^{K \times P}$.

$$
\mathbf{\underline{X}} = \sum_{q=1}^Q \sum_{r=1}^R \sum_{p=1}^P \mathbf{\underline{X}}_{qrp} = \sum_{q=1}^Q \sum_{r=1}^R \sum_{p=1}^P g_{qrp} \cdot \mathbf{a}_q \circ \mathbf{b}_r \circ \mathbf{c}_p
$$

The Tucker form of a tensor is closely related to the Kruskal representation and can be expressed through a 
sequence of mode-$n$ products in a similar way, that is

$$
\mathbf{\underline{X}} = \mathbf{\underline{G}} \times_1 \mathbf{A} \times_2 \mathbf{B} \times_3 \mathbf{C} = \Big[\mathbf{\underline{G}}; \mathbf{A}, \mathbf{B}, \mathbf{C} \Big]
$$


In [16]:
# Create factor matrices
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 2, 3, 4  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tCore tensor')
print(tensor_tkd.core)
tensor_tkd.core.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 4).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Core tensor
This tensor is of order 3 and consists of 24 elements.
Sizes and names of its modes are (2, 3, 4) and ['mode-0', 'mode-1', 'mode-2'] respectively.


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## **Assigment 2**

1. Core tensor of a Tucker representation consists of 1848 elements. Explain what tensor order should a tensor have to able to be represented in such form.

2. For a 4-th order tensor that consists of 1000 elements, provide three different Tucker representations.

3. For a 3-rd order tensor that consists of 500 elements, provide three different Tucker representations given that its core tensor consists of 42 elements.

4. Provide an intuition behind the main difference between the Tucker and Kruskal representations.


### Solution: Part 1

In [1]:
answer_2_1 = "The tensor order is does not affect the number of elements in the core tensor. The multiplication of all the multi-linear rank of the tensor should be equal to 1848. Any combination is then possible."  # use this variable for your answer

print(answer_2_1)

The tensor order is does not affect the number of elements in the core tensor. The multiplication of all the multi-linear rank of the tensor should be equal to 1848. Any combination is then possible.


### Solution: Part 2

In [21]:
# First representation
I, J, K, L = 10, 10, 5, 2  # define shape of the tensor in full form
Q, R, P, S = 2, 3, 4, 5  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D = np.arange(L * S).reshape(L, S)
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)
print(tensor_tkd)

tensor_full = tensor_tkd.reconstruct()
print(tensor_full)

Tucker representation of a tensor with multi-linear rank=(2, 3, 4, 5).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (10, 10, 5, 2) features respectively.
This tensor is of order 4 and consists of 1000 elements.
Sizes and names of its modes are (10, 10, 5, 2) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


In [23]:
# Second representation
I, J, K, L = 10, 10, 5, 2  # define shape of the tensor in full form
Q, R, P, S = 3, 2, 4, 5  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D = np.arange(L * S).reshape(L, S)
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)
print(tensor_tkd)

tensor_full = tensor_tkd.reconstruct()
print(tensor_full)

Tucker representation of a tensor with multi-linear rank=(3, 2, 4, 5).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (2, 10, 5, 10) features respectively.
This tensor is of order 4 and consists of 1000 elements.
Sizes and names of its modes are (2, 10, 5, 10) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


In [24]:
# Third representation
I, J, K, L = 10, 10, 5, 2  # define shape of the tensor in full form
Q, R, P, S = 3, 1, 7, 2  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D = np.arange(L * S).reshape(L, S)
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)
print(tensor_tkd)

tensor_full = tensor_tkd.reconstruct()
print(tensor_full)

Tucker representation of a tensor with multi-linear rank=(3, 1, 7, 2).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (2, 10, 5, 10) features respectively.
This tensor is of order 4 and consists of 1000 elements.
Sizes and names of its modes are (2, 10, 5, 10) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


### Solution: Part 3

In [25]:
# First representation
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 2, 3, 7  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tCore tensor')
print(tensor_tkd.core)
tensor_tkd.core.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 7).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (2, 3, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.


array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]]])

In [26]:
# Second representation
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 21, 1, 2  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tCore tensor')
print(tensor_tkd.core)
tensor_tkd.core.data

Tucker representation of a tensor with multi-linear rank=(21, 1, 2).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (21, 1, 2) and ['mode-0', 'mode-1', 'mode-2'] respectively.


array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]],

       [[12, 13]],

       [[14, 15]],

       [[16, 17]],

       [[18, 19]],

       [[20, 21]],

       [[22, 23]],

       [[24, 25]],

       [[26, 27]],

       [[28, 29]],

       [[30, 31]],

       [[32, 33]],

       [[34, 35]],

       [[36, 37]],

       [[38, 39]],

       [[40, 41]]])

In [27]:
# Third representation
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 3, 7, 2  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tCore tensor')
print(tensor_tkd.core)
tensor_tkd.core.data

Tucker representation of a tensor with multi-linear rank=(3, 7, 2).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (3, 7, 2) and ['mode-0', 'mode-1', 'mode-2'] respectively.


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41]]])

### Solution: Part 4

In [21]:
answer_2_4 = "The main difference between Kruskal and Tucker decomposition is the presence of the core tensor with Tucker having multi-linear ranks. This allows for column vectors of mode matrices to interact with each other for reconstruction"  # use this variable for your answer

print(answer_2_4)

ANSWER GOES HERE
